# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b8dd3f436685a571f9f744546f3e545ffac3f17f0b7a40821a19292d306f52205812bba2e0ef5eccee85bf13398dc88ab41fbbc2505ca1132f108b16e4b4551

test:
  secret_key_base: 50186642c539c65e3533df3924e06176893e5e31cfe3c8f436466be09310e91910c109c86e265d8b4bd7d0109124568b9d15d7b7af3fefe15911acddab35f835

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
